name: Publish snapshot

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-snapshot:
    # macos-latest is too slow. -14 will become latest in Q2 '24
    runs-on: macos-14
    if: github.repository == 'square/workflow-kotlin'
    timeout-minutes: 35

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: gradle/wrapper-validation-action@v1

      - name: Check for -SNAPSHOT version
        uses: ./.github/actions/gradle-task
        with:
          task: checkVersionIsSnapshot
          write-cache-key: build-logic

      - name: Assemble
        uses: ./.github/actions/gradle-task
        with:
          task: assemble
          write-cache-key: main-build-artifacts

      - name: Check
        uses: ./.github/actions/gradle-task
        with:
          task: check -x artifactsCheck

      - name: Publish Snapshots
        uses: ./.github/actions/gradle-task
        with:
          task: publish
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
