name: Publish snapshot

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - ray/ui-update

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx5g -Dorg.gradle.daemon=false -Dorg.gradle.logging.stacktrace=all"

jobs:
  publish-snapshot :
    runs-on : macos-latest
    if : github.repository == 'square/workflow-kotlin'
    timeout-minutes : 35

    steps :
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name : Check for -SNAPSHOT version
        uses : gradle/gradle-build-action@v2
        with :
          arguments : checkVersionIsSnapshot
          cache-read-only: false

      - name : Assemble
        uses : gradle/gradle-build-action@v2
        with :
          arguments : assemble
          cache-read-only: false

      - name : Check
        uses : gradle/gradle-build-action@v2
        with :
          arguments : check
          cache-read-only: false

      - name : Publish Snapshots
        uses : gradle/gradle-build-action@v2
        with :
          arguments : publish
          cache-read-only: false
        env :
          ORG_GRADLE_PROJECT_mavenCentralUsername : ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword : ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
