name: Publish snapshot

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - ray/ui-update

jobs:
  publish-snapshot :
    runs-on : macos-latest
    if : github.repository == 'square/workflow-kotlin'
    timeout-minutes : 35

    steps :
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name : Check for -SNAPSHOT version
        run: ./gradlew checkVersionIsSnapshot --no-daemon

      - name : Publish Snapshots
        run: |
          ./gradlew build --no-daemon
          ./gradlew publish --no-daemon
        env :
          ORG_GRADLE_PROJECT_mavenCentralUsername : ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword : ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
