name: Publish snapshot

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-snapshot:
    runs-on: workflow-kotlin-test-runner-ubuntu-4core
    if: github.repository == 'square/workflow-kotlin'
    timeout-minutes: 35

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Check for -SNAPSHOT version
        uses: ./.github/actions/gradle-task
        with:
          task: checkVersionIsSnapshot
          write-cache-key: build-logic

      - name: Assemble
        uses: ./.github/actions/gradle-task
        with:
          task: assemble
          write-cache-key: main-build-artifacts

      - name: Check
        uses: ./.github/actions/gradle-task
        with:
          task: check -x artifactsCheck

      - name: Publish Snapshots
        uses: ./.github/actions/gradle-task
        with:
          task: publish
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
