name: Validate documentation site

on:
  pull_request:
    paths:
      # Rebuild when workflow configs change.
      - .github/workflows/validate-documentation.yml
      - '**.md'
      - lint_docs.sh
      - .markdownlint.rb

jobs:
  lint:
    name: Lint Markdown files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install dependencies
        run: gem install mdl
      - name: Lint docs
        run: ./lint_docs.sh
